name: Release

on:
  push:
    tags:
      - 'v*.*'

jobs:
  build_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"

    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        go build -o logfmt-${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.ref_name }}

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: ./logfmt-${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.ref_name }}
